# -*- coding: utf-8 -*-
"""aula3_LPC_Eloi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17ix4C3-Vz_qtUz1V22fFfHcn69uTKWE2
"""

# ETE PORTO DIGITAL
# DISCIPLINA: LPC1
# PROFESSOR: CLOVES
# ESTUDANTE: ELOI

print ('Olá, ETE Porto Digital!')